### ISSUE TITLE
RMi driver fan speed retrieval

### ISSUE THREAD

**Issue by mdlayher** [audiohacked/OpenCorsairLink#48]
https://github.com/audiohacked/OpenCorsairLink/blob/master/protocol/rmi/fan.c#L22

It appears that fan speed retrieval functionality is currently disabled for the RMi driver.  Is there a reason why?  It also appears the the fan RPMs parameter would need to be a pointer to a uint16.

**Comment by audiohacked** [comment]
The majority of the time the Fan RPM of the RMi will be zero. I haven't used the function so I didn't notice I didn't finish the function.

**Comment by mdlayher** [comment]
Seems like it works fine when enabled.  Should this be reopened to track that it's not enabled?

**Comment by audiohacked** [comment]
It's disabled because I know people are going to freak out if I enabled it and their PSU's fan speed is reading zero (which even while gaming it won't turn on). The RMi/HXi/AXi are currently designed to not run the Fan unless the PSU usage is over 60? percent; not even during my gaming sessions have I had my RM750i's fan turn on.
